/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;
import Funciones.Validacion;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Fung y Samuel Vergel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     *
     */
    public static Grafo appGrafo = new Grafo();

    /**
     *
     */
    public Inicio() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        updateCSV = new javax.swing.JButton();
        updateGraph = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("BIENVENIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        updateCSV.setText("Cargar CSV");
        updateCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCSVActionPerformed(evt);
            }
        });
        jPanel1.add(updateCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        updateGraph.setText("Cargar Ultimo Grafo");
        updateGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGraphActionPerformed(evt);
            }
        });
        jPanel1.add(updateGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void updateCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV", "csv"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] partes = linea.split(",");
                    if (partes.length == 3) {
                        String origen = partes[0].trim();
                        String destino = partes[1].trim();
                        String pesoStr = partes[2].trim();


                        if (!appGrafo.search(origen)) {
                            appGrafo.addVert(origen);
                        }

                        if (!appGrafo.search(destino)) {
                            appGrafo.addVert(destino);
                        }

                        Validacion validacion = new Validacion();
                        if (validacion.ValidarNumeros(pesoStr) != -1) {
                            int peso = validacion.ValidarNumeros(pesoStr);
                            appGrafo.addArist(origen, destino, peso);
                        }

                    }
                }

            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar el grafo: " + e.getMessage());
            }
            
            if(!appGrafo.isEmpty()){
                Menu menu = new Menu();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "No se cargo correctamente el archivo CSV.\nPuede que no tenga el formato correcto o este vacio.");
            }
        }
    }//GEN-LAST:event_updateCSVActionPerformed

    private void updateGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGraphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateGraphActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateCSV;
    private javax.swing.JButton updateGraph;
    // End of variables declaration//GEN-END:variables
}
