/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Andres Fung y Samuel Vergel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        updateCSV = new javax.swing.JButton();
        save = new javax.swing.JButton();
        agregarP = new javax.swing.JButton();
        nuevaInt = new javax.swing.JButton();
        bfs = new javax.swing.JButton();
        djisktra = new javax.swing.JButton();
        hubs = new javax.swing.JButton();
        mostrarGrafo = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        updateCSV.setText("Cargar CSV");
        jPanel1.add(updateCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, -1));

        save.setText("Guardar Cambios");
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, -1));

        agregarP.setText("Agregar Proteina");
        agregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPActionPerformed(evt);
            }
        });
        jPanel1.add(agregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, -1));

        nuevaInt.setText("Nueva Interaccion");
        nuevaInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaIntActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 240, -1));

        bfs.setText("Busqueda por Anchura (BFS)");
        jPanel1.add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, -1));

        djisktra.setText("Djisktra");
        jPanel1.add(djisktra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 240, -1));

        hubs.setText("Identificacion de Hubs");
        jPanel1.add(hubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 240, -1));

        mostrarGrafo.setText("Mostrar Grafo");
        mostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 240, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void mostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGrafoActionPerformed
        Mostrar mostrar = new Mostrar();
        this.dispose();
    }//GEN-LAST:event_mostrarGrafoActionPerformed

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPActionPerformed
        AgregarProteina agregar = new AgregarProteina();
        this.dispose();
    }//GEN-LAST:event_agregarPActionPerformed

    private void nuevaIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaIntActionPerformed
        NuevaConexion nuevaC = new NuevaConexion();
        this.dispose();
    }//GEN-LAST:event_nuevaIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarP;
    private javax.swing.JButton bfs;
    private javax.swing.JButton djisktra;
    private javax.swing.JButton exit;
    private javax.swing.JButton hubs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarGrafo;
    private javax.swing.JButton nuevaInt;
    private javax.swing.JButton save;
    private javax.swing.JButton updateCSV;
    // End of variables declaration//GEN-END:variables
}
