/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Arista;
import EDD.Vertice;
import static Interfaces.Inicio.appGrafo;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Andres Fung y Samuel Vergel
 */
public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        System.setProperty("org.graphstream.ui", "swing");
        this.mostrar();
    }

    private void mostrar() {
        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("RedProteinas");

        // Atributos del grafo (Tamano y colores)
        graph.setAttribute("ui.stylesheet", "node { "
                + "   fill-color: #4472C4; " + "   size: 30px; " + "   text-size: 12px; "
                + "   text-color: white; " + "   text-alignment: center; "
                + "   text-background-mode: none; " + "   stroke-mode: plain; "
                + "   stroke-color: #2F5597; " + "}" + "edge { " + "   fill-color: #999999; "
                + "   text-size: 13px; " + "   text-color: #C00000; "
                + "   text-alignment: along; " + "   text-background-mode: rounded-box; "
                + "   text-background-color: white; " + "}");

        for (int i = 0; i < appGrafo.getVerts().getSize(); i++) {
            Vertice currentV = (Vertice) appGrafo.getVerts().getValue(i);
            if (graph.getNode(currentV.getNombre()) == null) {
                graph.addNode(currentV.getNombre()).setAttribute("ui.label", currentV.getNombre());
            }

            if (!currentV.getLad().isEmpty()) {
                for (int j = 0; j < currentV.getLad().getSize(); j++) {
                    Arista currentArt = (Arista) currentV.getLad().getValue(j);
                    Vertice currentDest = appGrafo.numVert(currentArt.getDestino());
                    
                    if (graph.getNode(currentDest.getNombre()) == null) {
                        graph.addNode(currentDest.getNombre()).setAttribute("ui.label", currentDest.getNombre());
                    }

                    String arista = currentV.getNombre() + "-" + currentDest.getNombre();
                    String arista2 = currentDest.getNombre() + "-" + currentV.getNombre();
                    //System.out.println(arista);
                    if (graph.getEdge(arista) == null && graph.getEdge(arista2) == null) {
                        Edge e = graph.addEdge(arista, currentV.getNombre(), currentDest.getNombre());
                        e.setAttribute("ui.label", currentArt.getPeso());
                    }

                }
            }
        }

        // Fisicas del grafo que no sirven pa nada porque el grafo hace lo que le sale del culoo
        graph.setAttribute("layout.force", 0.2);
        graph.setAttribute("layout.quality", 4);
        graph.setAttribute("layout.stabilization", 0.2);
        SwingViewer interfaz = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        interfaz.enableAutoLayout();
        Component viewPanel = (java.awt.Component) interfaz.addDefaultView(false);

        panelGrafo.removeAll();
        panelGrafo.setLayout(new java.awt.BorderLayout());
        panelGrafo.add(viewPanel, java.awt.BorderLayout.CENTER);
        panelGrafo.revalidate();
        panelGrafo.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelGrafo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        javax.swing.GroupLayout panelGrafoLayout = new javax.swing.GroupLayout(panelGrafo);
        panelGrafo.setLayout(panelGrafoLayout);
        panelGrafoLayout.setHorizontalGroup(
            panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        panelGrafoLayout.setVerticalGroup(
            panelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(panelGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 440, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelGrafo;
    // End of variables declaration//GEN-END:variables
}
