/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Vertice;
import Funciones.Validacion;
import static Interfaces.Inicio.appGrafo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Fung y Samuel Vergel
 */
public class NuevaConexion extends javax.swing.JFrame {

    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloCombo2 = new DefaultComboBoxModel();

    /**
     *
     */
    public NuevaConexion() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.actualizarModeloCombo();
    }

    private void actualizarModeloCombo() {
        modeloCombo.removeAllElements();
        modeloCombo2.removeAllElements();

        if (!appGrafo.isEmpty()) {
            for (int i = 0; i < appGrafo.getVerts().getSize(); i++) {
                Vertice verticeActual = (Vertice) appGrafo.getVerts().getValue(i);
                modeloCombo.addElement(verticeActual.getNombre());
            }

            if (modeloCombo.getSize() > 0) {
                proteinaOrigen.setSelectedIndex(0);
                actualizarComboDestino();
            }
        }
    }

    private void actualizarComboDestino() {
        modeloCombo2.removeAllElements();

        if (!appGrafo.isEmpty()) {
            String proteinaO = (String) proteinaOrigen.getSelectedItem();

            for (int i = 0; i < appGrafo.getVerts().getSize(); i++) {
                Vertice verticeActual = (Vertice) appGrafo.getVerts().getValue(i);
                String nombre = verticeActual.getNombre();

                //No agregamos la proteina principal en el combo de "destinoS"
                if (!nombre.equals(proteinaO)) {
                    modeloCombo2.addElement(nombre);
                }
            }

            if (modeloCombo2.getSize() > 0) {
                proteinaDestino.setSelectedIndex(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        proteinaOrigen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        proteinaDestino = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pesoInput = new javax.swing.JTextField();
        agregarConexion = new javax.swing.JButton();
        volverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Nueva Conexion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setText("Seleccione la Proteina Origen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        proteinaOrigen.setModel(modeloCombo);
        jPanel1.add(proteinaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 300, -1));

        jLabel3.setText("Seleccion la Proteina Destino:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        proteinaDestino.setModel(modeloCombo2);
        jPanel1.add(proteinaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 300, -1));

        jLabel4.setText("Peso de la Conexion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        jPanel1.add(pesoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 300, -1));

        agregarConexion.setText("Agregar Conexion");
        agregarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarConexionActionPerformed(evt);
            }
        });
        jPanel1.add(agregarConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 310, -1));

        volverMenu.setText("Volver al Menu");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(volverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    private void agregarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarConexionActionPerformed
        String nombreO = (String) proteinaOrigen.getSelectedItem();
        String nombreD = (String) proteinaDestino.getSelectedItem();
        Validacion validar = new Validacion();
        if(validar.ValidarNumeros(pesoInput.getText()) != -1){
            int peso = validar.ValidarNumeros(pesoInput.getText());
            appGrafo.addArist(nombreD, nombreO, peso);
            JOptionPane.showMessageDialog(null, "Conexion agregada correctamente.");
        }else{
            JOptionPane.showMessageDialog(null, "El peso debe ser un numero entero psoitivo.");
        }
    }//GEN-LAST:event_agregarConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaConexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarConexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pesoInput;
    private javax.swing.JComboBox<String> proteinaDestino;
    private javax.swing.JComboBox<String> proteinaOrigen;
    private javax.swing.JButton volverMenu;
    // End of variables declaration//GEN-END:variables
}
